spring.application.name=discovery-service
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.metadata-map.github.repo=arthurmarcolin/microservices-java

info.app.name=${spring.application.name}
info.app.description=Microservice com a função de atuar como um servidor de descoberta de servicos dentro de uma arquitetura de microservicos.
info.app.autor=Arthur Marcolin
