ALTER TABLE tb_product
  ADD COLUMN IF NOT EXISTS seller_id   VARCHAR(255),
  ADD COLUMN IF NOT EXISTS seller_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS categoria   VARCHAR(100),
  ADD COLUMN IF NOT EXISTS condicao    VARCHAR(50),
  ADD COLUMN IF NOT EXISTS cidade      VARCHAR(100),
  ADD COLUMN IF NOT EXISTS estado      VARCHAR(10);
