spring.application.name=order-service
server.port=8300

spring.datasource.url=jdbc:postgresql://localhost/bd_orders
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.locations=classpath:db_migration

eureka.client.service-url.default-zone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.healthcheck.enabled=true

spring.cloud.openfeign.client.config.product-service.connect-timeout=2000
spring.cloud.openfeign.client.config.product-service.read-timeout=5000
spring.cloud.openfeign.client.config.currency-service.connect-timeout=2000
spring.cloud.openfeign.client.config.currency-service.read-timeout=5000
spring.cloud.openfeign.circuitbreaker.enabled=true

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=200,expireAfterWrite=30s

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=${spring.application.name}
info.app.description=EletroHub — Gestão de pedidos
